"""assigment/task table

Revision ID: 459393f68838
Revises: 8372a0ae9e08
Create Date: 2020-04-25 16:00:10.464664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459393f68838'
down_revision = '8372a0ae9e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutle', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=140), nullable=True),
    sa.Column('due_date', sa.String(length=64), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('assignment')
    # ### end Alembic commands ###
