"""delete columns

Revision ID: 4d0d897e8da6
Revises: 387c94576d21
Create Date: 2020-05-01 20:34:14.178434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0d897e8da6'
down_revision = '387c94576d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'due')
    # ### end Alembic commands ###
