"""table upgrade -- issues

Revision ID: 583b5467ed65
Revises: 459393f68838
Create Date: 2020-04-25 16:23:39.210118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583b5467ed65'
down_revision = '459393f68838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'creator')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creator', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['creator'], ['id'])
    op.add_column('assignment', sa.Column('creator', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###
